//-----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ManifestToCode tool.
//     Tool Version: 14.0.50929.2
// </auto-generated>
//-----------------------------------------------------------------------------

using System;

namespace net.adamec.dev.vs.extension.radprojects.ui
{
    public static class ResourceImageIds
    {
        public static readonly Guid AssetsGuid = new Guid("{4902317a-9f9e-48ad-88c4-78f715a553d1}");

        public const int Active = 0;
        public const int ClearConsole = 1;
        public const int Detail = 2;
        public const int Evaluate = 3;
        public const int FinishedNok = 4;
        public const int FinishedOk = 5;
        public const int Manual = 6;
        public const int Pending = 7;
        public const int Refresh = 8;
        public const int Reset = 9;
        public const int ResultNok = 10;
        public const int ResultOk = 11;
        public const int Run = 12;
        public const int Running = 13;
        public const int Skip = 14;
        public const int Skipped = 15;
    }
}
